In [2]:
import pandas as pd
import numpy as np

Numpy

In [3]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [4]:
# creating 1d aray
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
a.shape

(5,)

In [6]:
# creating 2d array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
b.shape

(2, 4)

In [8]:
# creating an array of Zeros
x=np.zeros((3,3), dtype = int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
# creating an array of Ones
x=np.ones((3,3), dtype = int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
# creating an array with a specific value
x=np.full((3,3),4)
print(x)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [11]:
# printing identity matrix
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# matrix with random values
x=np.random.randint(10,100,(3,2))
print(x)

[[69 37]
 [41 48]
 [80 25]]


Array Manipulation

In [18]:
trans = np.transpose(x)
print(trans)

[[69 41 80]
 [37 48 25]]


In [19]:
b=trans.reshape(3,2)
print(b)

[[69 41]
 [80 37]
 [48 25]]


In [20]:
pd.DataFrame(b)

0   1
0  69  41
1  80  37
2  48  25

In [26]:
data={
    'name': ['Akshay','Mahesh','Akash', 'sarma','Jayanth'],
    'age' :np.random.randint(18,30,5),
    'salary' :np.random.randint(50000,90000,5)
}
df=pd.DataFrame(data)
df

name  age  salary
0   Akshay   29   88613
1   Mahesh   18   82987
2    Akash   26   68506
3    sarma   22   86036
4  Jayanth   28   61137

In [27]:
df['Address']= ['Kamareddy','warangal','nizamabad','Kamareddy','warangal']

In [28]:
df

name  age  salary    Address
0   Akshay   29   88613  Kamareddy
1   Mahesh   18   82987   warangal
2    Akash   26   68506  nizamabad
3    sarma   22   86036  Kamareddy
4  Jayanth   28   61137   warangal

In [44]:
df.groupby('Address')['name'].unique()

Address
Kamareddy      [Akshay, sarma]
nizamabad              [Akash]
warangal     [Mahesh, Jayanth]
Name: name, dtype: object

In [45]:
df.shape

(5, 4)

In [47]:
df.drop(columns='age')

name  salary    Address
0   Akshay   88613  Kamareddy
1   Mahesh   82987   warangal
2    Akash   68506  nizamabad
3    sarma   86036  Kamareddy
4  Jayanth   61137   warangal

In [48]:
df

name  age  salary    Address
0   Akshay   29   88613  Kamareddy
1   Mahesh   18   82987   warangal
2    Akash   26   68506  nizamabad
3    sarma   22   86036  Kamareddy
4  Jayanth   28   61137   warangal

In [56]:
df.iloc[1,0]

'Mahesh'

Matpoltlib